### ISSUE TITLE
RuntimeError: Type not yet supported: typing.Literal['sgd', 'adamw', 'adam']

### ISSUE THREAD

**Issue by cvmilesight** [roboflow/maestro#61]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar feature requests.

### Question

I saw a commit:https://github.com/roboflow/multimodal-maestro/commit/59c99fcfcd325e725f73871dfe0243a969ee7b2d, But the most recent version of Typer (V0.12.5) currently lacks support for "typing.Literal". I noticed that the associated pull request has not yet been merged: https://github.com/fastapi/typer/pull/429. Am I possibly misunderstanding something?

### Additional

OS:ubuntu 20.04
python 3.10
typer 0.12.5
click 8.1.7

**Comment by SkalskiP** [comment]
Hi @cvmilesight 👋🏻 Thanks a lot for being vigilant! This change was accidentally introduced during the `mypy` check integration. We're already working on a [fix](https://github.com/roboflow/maestro/pull/63).

**Comment by SkalskiP** [comment]
The fix got merged. I'm closing this issue.
