### ISSUE TITLE
Does maestro no longer support or focus on SoM

### ISSUE THREAD

**Issue by antoan** [roboflow/maestro#85]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar feature requests.

### Question

maestro's focus seems to have shifted since I last looked at it after reading the following blog post
https://blog.roboflow.com/multimodal-maestro-advanced-lmm-prompting/

Is it no longer about visual prompting?

**Comment by SkalskiP** [comment]
Hi @antoan 👋🏻 It's nice to see you're interested in maestro. Yes, in the meantime we decided to change the profile of the library. We noticed that training VLMs requires a fair amount of knowledge and we decided to focus primarily on simplifying this process.
